<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Hotels [
<!ELEMENT Hotels (Hotel+)>
<!ELEMENT Hotel (Name, (Phone+), Address)>
<!ATTLIST Hotel Rating CDATA #IMPLIED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Address (Number, Street, City, State, Zip)>
<!ATTLIST Address NearestAirport CDATA #REQUIRED>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
]>
<Hotel>
	<Hotel>
		<Name>Westin</Name>
		<Phone>480-968-8885</Phone>
		<Phone>800-937-8461</Phone>
		<Address>
			<Number>11</Number>
			<Street>E. 7th St</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
		<Rating>4.2</Rating>
	</Hotel>
	<Hotel>
		<Name>Moxy</Name>
		<Phone>480-968-3451</Phone>
		<Address>
			<Number>1333</Number>
			<Street>S Rural Rd</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Hyatt Place</Name>
		<Phone>480-207-1578</Phone>
		<Phone>800-233-1234</Phone>
		<Address>
			<Number>601</Number>
			<Street>E 6th St</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
		<Rating>4.3</Rating>
	</Hotel>
	<Hotel>
		<Name>University Inn</Name>
		<Phone>480-966-7221</Phone>
		<Address>
			<Number>902</Number>
			<Street>S Mill Ave</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
		<Rating>4.4</Rating>
	</Hotel>
	<Hotel>
		<Name>Canopy by Hilton</Name>
		<Name>Canopy</Name>
		<Phone>480-968-6800</Phone>
		<Phone>888-446-6677</Phone>
		<Address>
			<Number>108</Number>
			<Street>E University Dr</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Omni</Name>
		<Phone>602-794-8600</Phone>
		<Address>
			<Number>7</Number>
			<Street>E University Dr</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Mission Palms, a Destination by Hyatt</Name>
		<Address>
			<Number>60</Number>
			<Street>E 5th St</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
		<Rating>4.4</Rating>
	</Hotel>
	<Hotel>
		<Name>Vib Hotel by Best Western</Name>
		<Phone>480-805-2070</Phone>
		<Phone>800-780-7234</Phone>
		<Address>
			<Number>511</Number>
			<Street>S Farmer Ave</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
		</Address>
	</Hotel>
	<Hotel>
		<Name>AC Hotel by Marriot</Name>
		<Phone>480-642-6140</Phone>
		<Address>
			<Number>100</Number>
			<Street>E Rio Salado Pkwy</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85281</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Holiday Inn Express</Name>
		<Phone>480-784-2233</Phone>
		<Phone>888-465-4329</Phone>
		<Address>
			<Number>670</Number>
			<Street>N Scottsdale Rd</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85288</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		<Rating>3.7</Rating>
	</Hotel>
	<Hotel>
		<Name>Comfort Inn and Suites</Name>
		<Phone>480-858-9898</Phone>
		<Address>
			<Number>808</Number>
			<Street>N Scottsdale Rd</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85288</Zip>
			<NearestAirport>Sky Harbor</NearestAirport>
		</Address>
	</Hotel>
	<Hotel>
		<Name>Motel 6</Name>
		<Phone>480-945-9506</Phone>
		<Address>
			<Number>1612</Number>
			<Street>N Scottsdale Rd</Street>
			<City>Tempe</City>
			<State>AZ</State>
			<Zip>85288</Zip>
		</Address>
		<Rating>4.3</Rating>
	</Hotel>
</Hotel>
